"""fixed added more embed settings

Revision ID: 0f81f8496956
Revises: fc6fc8969bb7
Create Date: 2026-06-21 11:06:11.714773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f81f8496956'
down_revision: Union[str, Sequence[str], None] = 'fc6fc8969bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('embed_primary_color', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('embed_bg_color', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('embed_text_color', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('embed_border_radius', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('embed_show_logo', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('embed_show_poweredBy', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('embed_email_placeholder', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('embed_width', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('embed_shadow', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'embed_shadow')
    op.drop_column('users', 'embed_width')
    op.drop_column('users', 'embed_email_placeholder')
    op.drop_column('users', 'embed_show_poweredBy')
    op.drop_column('users', 'embed_show_logo')
    op.drop_column('users', 'embed_border_radius')
    op.drop_column('users', 'embed_text_color')
    op.drop_column('users', 'embed_bg_color')
    op.drop_column('users', 'embed_primary_color')
    # ### end Alembic commands ###
