"""added visitor tracking

Revision ID: 10c9e6f9890e
Revises: 98310618ad0d
Create Date: 2026-04-10 07:49:53.729965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c9e6f9890e'
down_revision: Union[str, Sequence[str], None] = '98310618ad0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.String(length=500), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('visited_at', sa.DateTime(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('converted_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_converted'), 'visitors', ['converted'], unique=False)
    op.create_index(op.f('ix_visitors_country'), 'visitors', ['country'], unique=False)
    op.create_index(op.f('ix_visitors_country_code'), 'visitors', ['country_code'], unique=False)
    op.create_index(op.f('ix_visitors_id'), 'visitors', ['id'], unique=False)
    op.create_index(op.f('ix_visitors_ip_address'), 'visitors', ['ip_address'], unique=False)
    op.create_index(op.f('ix_visitors_visited_at'), 'visitors', ['visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitors_visited_at'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_ip_address'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_country_code'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_country'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_converted'), table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###
