"""added embedded audits model with api key

Revision ID: 13b50efd0c53
Revises: 10c9e6f9890e
Create Date: 2026-04-17 17:44:43.494476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13b50efd0c53'
down_revision: Union[str, Sequence[str], None] = '10c9e6f9890e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embed_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embed_leads_created_at'), 'embed_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_embed_leads_email'), 'embed_leads', ['email'], unique=False)
    op.create_index(op.f('ix_embed_leads_id'), 'embed_leads', ['id'], unique=False)
    # op.drop_index(op.f('ix_embed_tokens_id'), table_name='embed_tokens')
    # op.drop_index(op.f('ix_embed_tokens_token'), table_name='embed_tokens')
    # op.drop_table('embed_tokens')
    op.add_column('audits', sa.Column('is_embedded', sa.Boolean(), nullable=True))
    op.add_column('audits', sa.Column('embed_email', sa.String(length=255), nullable=True))
    # op.drop_constraint(op.f('audits_embed_token_id_fkey'), 'audits', type_='foreignkey')
    op.drop_column('audits', 'embed_token_id')
    op.add_column('users', sa.Column('embed_api_key', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('embed_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('embed_lead_capture', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('embed_require_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('embed_button_text', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('embed_headline', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('embed_description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_users_embed_api_key'), 'users', ['embed_api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_embed_api_key'), table_name='users')
    op.drop_column('users', 'embed_description')
    op.drop_column('users', 'embed_headline')
    op.drop_column('users', 'embed_button_text')
    op.drop_column('users', 'embed_require_email')
    op.drop_column('users', 'embed_lead_capture')
    op.drop_column('users', 'embed_enabled')
    op.drop_column('users', 'embed_api_key')
    op.add_column('audits', sa.Column('embed_token_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('audits_embed_token_id_fkey'), 'audits', 'embed_tokens', ['embed_token_id'], ['id'])
    op.drop_column('audits', 'embed_email')
    op.drop_column('audits', 'is_embedded')
    op.create_table('embed_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('agency_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('agency_logo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('accent_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('show_branding', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('custom_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('monthly_audits_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_month_audits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('callback_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allowed_domains', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('embed_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('embed_tokens_pkey')),
    sa.UniqueConstraint('custom_domain', name=op.f('embed_tokens_custom_domain_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_embed_tokens_token'), 'embed_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_embed_tokens_id'), 'embed_tokens', ['id'], unique=False)
    op.drop_index(op.f('ix_embed_leads_id'), table_name='embed_leads')
    op.drop_index(op.f('ix_embed_leads_email'), table_name='embed_leads')
    op.drop_index(op.f('ix_embed_leads_created_at'), table_name='embed_leads')
    op.drop_table('embed_leads')
    # ### end Alembic commands ###
