"""added fields to comparisons

Revision ID: 301c8f874fe5
Revises: d6d8b548f732
Create Date: 2026-06-30 02:28:05.021954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301c8f874fe5'
down_revision: Union[str, Sequence[str], None] = 'd6d8b548f732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparisons', sa.Column('target_score', sa.Integer(), nullable=True))
    op.add_column('comparisons', sa.Column('best_competitor_score', sa.Integer(), nullable=True))
    op.add_column('comparisons', sa.Column('best_competitor_url', sa.String(length=500), nullable=True))
    op.add_column('comparisons', sa.Column('worst_competitor_score', sa.Integer(), nullable=True))
    op.add_column('comparisons', sa.Column('avg_competitor_score', sa.Float(), nullable=True))
    op.add_column('comparisons', sa.Column('score_gap', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparisons', 'score_gap')
    op.drop_column('comparisons', 'avg_competitor_score')
    op.drop_column('comparisons', 'worst_competitor_score')
    op.drop_column('comparisons', 'best_competitor_url')
    op.drop_column('comparisons', 'best_competitor_score')
    op.drop_column('comparisons', 'target_score')
    # ### end Alembic commands ###
