"""added email sequences

Revision ID: 36a608f0fdc0
Revises: dfd4d651a805
Create Date: 2026-07-12 14:17:34.263903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36a608f0fdc0'
down_revision: Union[str, Sequence[str], None] = 'dfd4d651a805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_seq_welcome_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_seq_day1_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_seq_day3_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_seq_day7_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_seq_day14_sent_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('email_seq_unsubscribed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('seq_welcome_sent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('seq_day1_sent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('seq_day3_sent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('seq_day7_sent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('seq_day14_sent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('seq_unsubscribed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('seq_unsubscribe_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_seq_unsubscribe_token'), 'users', ['seq_unsubscribe_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_seq_unsubscribe_token'), table_name='users')
    op.drop_column('users', 'seq_unsubscribe_token')
    op.drop_column('users', 'seq_unsubscribed')
    op.drop_column('users', 'seq_day14_sent')
    op.drop_column('users', 'seq_day7_sent')
    op.drop_column('users', 'seq_day3_sent')
    op.drop_column('users', 'seq_day1_sent')
    op.drop_column('users', 'seq_welcome_sent')
    op.drop_column('users', 'email_seq_unsubscribed')
    op.drop_column('users', 'email_seq_day14_sent_at')
    op.drop_column('users', 'email_seq_day7_sent_at')
    op.drop_column('users', 'email_seq_day3_sent_at')
    op.drop_column('users', 'email_seq_day1_sent_at')
    op.drop_column('users', 'email_seq_welcome_sent_at')
    # ### end Alembic commands ###
