"""updated ranktracking

Revision ID: 48e7af5e350a
Revises: 4bf69f225246
Create Date: 2026-06-25 23:12:25.777702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48e7af5e350a'
down_revision: Union[str, Sequence[str], None] = '4bf69f225246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('previous_position', sa.Integer(), nullable=True),
    sa.Column('position_change', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_id'], ['rank_trackings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_history_checked_at'), 'rank_history', ['checked_at'], unique=False)
    op.create_index(op.f('ix_rank_history_id'), 'rank_history', ['id'], unique=False)
    op.create_index(op.f('ix_rank_history_keyword'), 'rank_history', ['keyword'], unique=False)
    op.add_column('rank_trackings', sa.Column('keywords', sa.JSON(), nullable=False))
    op.add_column('rank_trackings', sa.Column('engines', sa.JSON(), nullable=False))
    op.add_column('rank_trackings', sa.Column('frequency', sa.String(length=20), nullable=True))
    op.add_column('rank_trackings', sa.Column('is_scheduled', sa.Boolean(), nullable=True))
    op.add_column('rank_trackings', sa.Column('next_check', sa.DateTime(), nullable=True))
    op.add_column('rank_trackings', sa.Column('last_checked', sa.DateTime(), nullable=True))
    op.drop_column('rank_trackings', 'last_checked_at')
    op.drop_column('rank_trackings', 'search_engines')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank_trackings', sa.Column('search_engines', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('rank_trackings', sa.Column('last_checked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('rank_trackings', 'last_checked')
    op.drop_column('rank_trackings', 'next_check')
    op.drop_column('rank_trackings', 'is_scheduled')
    op.drop_column('rank_trackings', 'frequency')
    op.drop_column('rank_trackings', 'engines')
    op.drop_column('rank_trackings', 'keywords')
    op.drop_index(op.f('ix_rank_history_keyword'), table_name='rank_history')
    op.drop_index(op.f('ix_rank_history_id'), table_name='rank_history')
    op.drop_index(op.f('ix_rank_history_checked_at'), table_name='rank_history')
    op.drop_table('rank_history')
    # ### end Alembic commands ###
