"""added whop

Revision ID: 5f4e7fefc93a
Revises: 13b50efd0c53
Create Date: 2026-04-29 06:24:12.965212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4e7fefc93a'
down_revision: Union[str, Sequence[str], None] = '13b50efd0c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('whop_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('whop_product_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('subscription_started_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('subscription_renews_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('whop_metadata', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_users_whop_subscription_id'), 'users', ['whop_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_whop_subscription_id'), table_name='users')
    op.drop_column('users', 'whop_metadata')
    op.drop_column('users', 'subscription_renews_at')
    op.drop_column('users', 'subscription_started_at')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'whop_product_id')
    op.drop_column('users', 'whop_subscription_id')
    # ### end Alembic commands ###
