"""modified tracking rankings 3

Revision ID: 5ff0ab13dda1
Revises: c8655fd1a759
Create Date: 2026-06-28 05:47:04.822657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff0ab13dda1'
down_revision: Union[str, Sequence[str], None] = 'c8655fd1a759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank_trackings', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rank_trackings', 'name')
    # ### end Alembic commands ###
