"""added audit share link

Revision ID: 8a68f090c0be
Revises: c781521acf8b
Create Date: 2026-09-24 07:08:34.059113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a68f090c0be'
down_revision: Union[str, Sequence[str], None] = 'c781521acf8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_share_links_id'), 'audit_share_links', ['id'], unique=False)
    op.create_index(op.f('ix_audit_share_links_share_token'), 'audit_share_links', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_share_links_share_token'), table_name='audit_share_links')
    op.drop_index(op.f('ix_audit_share_links_id'), table_name='audit_share_links')
    op.drop_table('audit_share_links')
    # ### end Alembic commands ###
