"""modified tracking rankings

Revision ID: 8d61a6729e3c
Revises: 7f3d28d7e761
Create Date: 2026-06-26 18:22:58.903444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d61a6729e3c'
down_revision: Union[str, Sequence[str], None] = '7f3d28d7e761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
