"""added anonymous audits

Revision ID: 9000ef3118f1
Revises: ed2162821cd7
Create Date: 2026-07-01 13:40:48.094085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9000ef3118f1'
down_revision: Union[str, Sequence[str], None] = 'ed2162821cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('stage_label', sa.String(length=100), nullable=True),
    sa.Column('audit_score', sa.Integer(), nullable=True),
    sa.Column('audit_results', sa.JSON(), nullable=True),
    sa.Column('crawl_results', sa.JSON(), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=True),
    sa.Column('claimed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymous_audits_created_at'), 'anonymous_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_anonymous_audits_id'), 'anonymous_audits', ['id'], unique=False)
    op.create_index(op.f('ix_anonymous_audits_session_token'), 'anonymous_audits', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_audits_session_token'), table_name='anonymous_audits')
    op.drop_index(op.f('ix_anonymous_audits_id'), table_name='anonymous_audits')
    op.drop_index(op.f('ix_anonymous_audits_created_at'), table_name='anonymous_audits')
    op.drop_table('anonymous_audits')
    # ### end Alembic commands ###
