"""added client name to audits fields

Revision ID: 98310618ad0d
Revises: 339fbaef2dfe
Create Date: 2026-04-04 07:03:40.940561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98310618ad0d'
down_revision: Union[str, Sequence[str], None] = '339fbaef2dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('client_name', sa.String(length=255), nullable=True))
    op.add_column('comparisons', sa.Column('client_name', sa.String(length=255), nullable=True))
    op.add_column('crawls', sa.Column('client_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawls', 'client_name')
    op.drop_column('comparisons', 'client_name')
    op.drop_column('audits', 'client_name')
    # ### end Alembic commands ###
