"""added trial management

Revision ID: b02046c9cddd
Revises: b189f076a3d0
Create Date: 2026-05-12 03:29:21.795966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02046c9cddd'
down_revision: Union[str, Sequence[str], None] = 'b189f076a3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_started_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('trial_used', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('trial_plan', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('trial_email_sent_start', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('trial_email_sent_day3', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('trial_email_sent_day10', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('trial_email_sent_expiring_soon', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_email_sent_expiring_soon')
    op.drop_column('users', 'trial_email_sent_day10')
    op.drop_column('users', 'trial_email_sent_day3')
    op.drop_column('users', 'trial_email_sent_start')
    op.drop_column('users', 'trial_plan')
    op.drop_column('users', 'trial_used')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'trial_started_at')
    # ### end Alembic commands ###
