"""added fullname in embed leads model

Revision ID: b189f076a3d0
Revises: 5f4e7fefc93a
Create Date: 2026-05-02 01:05:06.887824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b189f076a3d0'
down_revision: Union[str, Sequence[str], None] = '5f4e7fefc93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embed_leads', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_embed_leads_full_name'), 'embed_leads', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embed_leads_full_name'), table_name='embed_leads')
    op.drop_column('embed_leads', 'full_name')
    # ### end Alembic commands ###
