"""updated again again ranktracking

Revision ID: c3f036cb9155
Revises: 1af76415a80e
Create Date: 2026-06-26 15:29:41.418784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f036cb9155'
down_revision: Union[str, Sequence[str], None] = '1af76415a80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('tracked_keywords',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('keyword', sa.String(length=500), nullable=False),
    # sa.Column('domain', sa.String(length=255), nullable=False),
    # sa.Column('engine', sa.String(length=50), nullable=True),
    # sa.Column('country', sa.String(length=10), nullable=True),
    # sa.Column('group_name', sa.String(length=100), nullable=True),
    # sa.Column('tags', sa.JSON(), nullable=True),
    # sa.Column('search_volume', sa.Integer(), nullable=True),
    # sa.Column('difficulty', sa.Float(), nullable=True),
    # sa.Column('current_position', sa.Integer(), nullable=True),
    # sa.Column('previous_position', sa.Integer(), nullable=True),
    # sa.Column('position_change', sa.Integer(), nullable=True),
    # sa.Column('best_position', sa.Integer(), nullable=True),
    # sa.Column('landing_url', sa.String(length=1000), nullable=True),
    # sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    # sa.Column('is_active', sa.Boolean(), nullable=True),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_tracked_keywords_created_at'), 'tracked_keywords', ['created_at'], unique=False)
    # op.create_index(op.f('ix_tracked_keywords_domain'), 'tracked_keywords', ['domain'], unique=False)
    # op.create_index(op.f('ix_tracked_keywords_id'), 'tracked_keywords', ['id'], unique=False)
    # op.create_index(op.f('ix_tracked_keywords_keyword'), 'tracked_keywords', ['keyword'], unique=False)
    # op.create_table('keyword_history',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('keyword_id', sa.Integer(), nullable=False),
    # sa.Column('position', sa.Integer(), nullable=True),
    # sa.Column('previous_position', sa.Integer(), nullable=True),
    # sa.Column('position_change', sa.Integer(), nullable=True),
    # sa.Column('landing_url', sa.String(length=1000), nullable=True),
    # sa.Column('title', sa.String(length=500), nullable=True),
    # sa.Column('engine', sa.String(length=50), nullable=False),
    # sa.Column('checked_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['keyword_id'], ['tracked_keywords.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_keyword_history_checked_at'), 'keyword_history', ['checked_at'], unique=False)
    # op.create_index(op.f('ix_keyword_history_id'), 'keyword_history', ['id'], unique=False)
    # op.create_table('tracking_keywords',
    # sa.Column('tracking_id', sa.Integer(), nullable=False),
    # sa.Column('keyword_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['keyword_id'], ['tracked_keywords.id'], ),
    # sa.ForeignKeyConstraint(['tracking_id'], ['rank_trackings.id'], ),
    # sa.PrimaryKeyConstraint('tracking_id', 'keyword_id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_keywords')
    op.drop_index(op.f('ix_keyword_history_id'), table_name='keyword_history')
    op.drop_index(op.f('ix_keyword_history_checked_at'), table_name='keyword_history')
    op.drop_table('keyword_history')
    op.drop_index(op.f('ix_tracked_keywords_keyword'), table_name='tracked_keywords')
    op.drop_index(op.f('ix_tracked_keywords_id'), table_name='tracked_keywords')
    op.drop_index(op.f('ix_tracked_keywords_domain'), table_name='tracked_keywords')
    op.drop_index(op.f('ix_tracked_keywords_created_at'), table_name='tracked_keywords')
    op.drop_table('tracked_keywords')
    # ### end Alembic commands ###
