"""added country to trackings

Revision ID: d6d8b548f732
Revises: 5ff0ab13dda1
Create Date: 2026-06-28 08:00:28.220285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d8b548f732'
down_revision: Union[str, Sequence[str], None] = '5ff0ab13dda1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rank_trackings', sa.Column('country', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rank_trackings', 'country')
    # ### end Alembic commands ###
