"""added fields on user

Revision ID: dfd4d651a805
Revises: 9000ef3118f1
Create Date: 2026-07-03 00:46:26.065366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd4d651a805'
down_revision: Union[str, Sequence[str], None] = '9000ef3118f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ob_audit_done', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ob_crawl_done', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ob_compare_done', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ob_tracking_done', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('ob_checklist_dismissed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ob_checklist_dismissed')
    op.drop_column('users', 'ob_tracking_done')
    op.drop_column('users', 'ob_compare_done')
    op.drop_column('users', 'ob_crawl_done')
    op.drop_column('users', 'ob_audit_done')
    # ### end Alembic commands ###
