"""Initial schema

Revision ID: ed2162821cd7
Revises: 
Create Date: 2026-06-30 05:32:26.654750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2162821cd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('agency_name', sa.String(length=255), nullable=True),
    sa.Column('agency_logo', sa.Text(), nullable=True),
    sa.Column('agency_url', sa.String(length=500), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('credits_remaining', sa.Integer(), nullable=True),
    sa.Column('credits_reset_date', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('whop_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('whop_product_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('subscription_started_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_renews_at', sa.DateTime(), nullable=True),
    sa.Column('whop_metadata', sa.JSON(), nullable=True),
    sa.Column('trial_started_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('trial_used', sa.Boolean(), nullable=True),
    sa.Column('trial_plan', sa.String(length=50), nullable=True),
    sa.Column('trial_email_sent_start', sa.Boolean(), nullable=True),
    sa.Column('trial_email_sent_day3', sa.Boolean(), nullable=True),
    sa.Column('trial_email_sent_day10', sa.Boolean(), nullable=True),
    sa.Column('trial_email_sent_expiring_soon', sa.Boolean(), nullable=True),
    sa.Column('embed_api_key', sa.String(length=255), nullable=True),
    sa.Column('embed_enabled', sa.Boolean(), nullable=True),
    sa.Column('embed_lead_capture', sa.Boolean(), nullable=True),
    sa.Column('embed_require_email', sa.Boolean(), nullable=True),
    sa.Column('embed_button_text', sa.String(length=100), nullable=True),
    sa.Column('embed_headline', sa.String(length=200), nullable=True),
    sa.Column('embed_description', sa.Text(), nullable=True),
    sa.Column('embed_primary_color', sa.String(length=200), nullable=True),
    sa.Column('embed_bg_color', sa.String(length=200), nullable=True),
    sa.Column('embed_text_color', sa.String(length=200), nullable=True),
    sa.Column('embed_border_radius', sa.Integer(), nullable=True),
    sa.Column('embed_show_logo', sa.Boolean(), nullable=True),
    sa.Column('embed_show_poweredBy', sa.Boolean(), nullable=True),
    sa.Column('embed_email_placeholder', sa.String(length=200), nullable=True),
    sa.Column('embed_width', sa.String(length=100), nullable=True),
    sa.Column('embed_shadow', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_embed_api_key'), 'users', ['embed_api_key'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_users_stripe_subscription_id'), 'users', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_users_whop_subscription_id'), 'users', ['whop_subscription_id'], unique=True)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('is_embedded', sa.Boolean(), nullable=True),
    sa.Column('embed_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_created_at'), 'audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.create_index(op.f('ix_audits_job_id'), 'audits', ['job_id'], unique=True)
    op.create_table('backlink_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('competitor_domains', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_backlinks', sa.Integer(), nullable=True),
    sa.Column('toxic_count', sa.Integer(), nullable=True),
    sa.Column('avg_quality_score', sa.Float(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backlink_analyses_created_at'), 'backlink_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_backlink_analyses_id'), 'backlink_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_backlink_analyses_job_id'), 'backlink_analyses', ['job_id'], unique=True)
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('competitor_urls', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('target_score', sa.Integer(), nullable=True),
    sa.Column('best_competitor_score', sa.Integer(), nullable=True),
    sa.Column('best_competitor_url', sa.String(length=500), nullable=True),
    sa.Column('worst_competitor_score', sa.Integer(), nullable=True),
    sa.Column('avg_competitor_score', sa.Float(), nullable=True),
    sa.Column('score_gap', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_created_at'), 'comparisons', ['created_at'], unique=False)
    op.create_index(op.f('ix_comparisons_id'), 'comparisons', ['id'], unique=False)
    op.create_index(op.f('ix_comparisons_job_id'), 'comparisons', ['job_id'], unique=True)
    op.create_table('crawls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('max_pages', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=True),
    sa.Column('issues_found', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawls_created_at'), 'crawls', ['created_at'], unique=False)
    op.create_index(op.f('ix_crawls_id'), 'crawls', ['id'], unique=False)
    op.create_index(op.f('ix_crawls_job_id'), 'crawls', ['job_id'], unique=True)
    op.create_table('keyword_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_opportunities', sa.Integer(), nullable=True),
    sa.Column('estimated_traffic_gain', sa.Integer(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_analyses_created_at'), 'keyword_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_keyword_analyses_id'), 'keyword_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_keyword_analyses_job_id'), 'keyword_analyses', ['job_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('rank_trackings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('engines', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total_keywords', sa.Integer(), nullable=True),
    sa.Column('keywords_found', sa.Integer(), nullable=True),
    sa.Column('avg_position', sa.Float(), nullable=True),
    sa.Column('best_position', sa.Integer(), nullable=True),
    sa.Column('worst_position', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('is_scheduled', sa.Boolean(), nullable=True),
    sa.Column('next_check', sa.DateTime(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_trackings_created_at'), 'rank_trackings', ['created_at'], unique=False)
    op.create_index(op.f('ix_rank_trackings_domain'), 'rank_trackings', ['domain'], unique=False)
    op.create_index(op.f('ix_rank_trackings_id'), 'rank_trackings', ['id'], unique=False)
    op.create_index(op.f('ix_rank_trackings_job_id'), 'rank_trackings', ['job_id'], unique=True)
    op.create_index(op.f('ix_rank_trackings_status'), 'rank_trackings', ['status'], unique=False)
    op.create_index(op.f('ix_rank_trackings_user_id'), 'rank_trackings', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('tracked_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('search_volume', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('previous_position', sa.Integer(), nullable=True),
    sa.Column('position_change', sa.Integer(), nullable=True),
    sa.Column('best_position', sa.Integer(), nullable=True),
    sa.Column('landing_url', sa.String(length=1000), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_keywords_created_at'), 'tracked_keywords', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracked_keywords_domain'), 'tracked_keywords', ['domain'], unique=False)
    op.create_index(op.f('ix_tracked_keywords_id'), 'tracked_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_tracked_keywords_keyword'), 'tracked_keywords', ['keyword'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=True)
    op.create_table('visitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referer', sa.String(length=500), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('visited_at', sa.DateTime(), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('converted_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_converted'), 'visitors', ['converted'], unique=False)
    op.create_index(op.f('ix_visitors_country'), 'visitors', ['country'], unique=False)
    op.create_index(op.f('ix_visitors_country_code'), 'visitors', ['country_code'], unique=False)
    op.create_index(op.f('ix_visitors_id'), 'visitors', ['id'], unique=False)
    op.create_index(op.f('ix_visitors_ip_address'), 'visitors', ['ip_address'], unique=False)
    op.create_index(op.f('ix_visitors_visited_at'), 'visitors', ['visited_at'], unique=False)
    op.create_table('embed_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embed_leads_created_at'), 'embed_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_embed_leads_email'), 'embed_leads', ['email'], unique=False)
    op.create_index(op.f('ix_embed_leads_full_name'), 'embed_leads', ['full_name'], unique=False)
    op.create_index(op.f('ix_embed_leads_id'), 'embed_leads', ['id'], unique=False)
    op.create_table('keyword_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('previous_position', sa.Integer(), nullable=True),
    sa.Column('position_change', sa.Integer(), nullable=True),
    sa.Column('landing_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['tracked_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_history_checked_at'), 'keyword_history', ['checked_at'], unique=False)
    op.create_index(op.f('ix_keyword_history_id'), 'keyword_history', ['id'], unique=False)
    op.create_table('rank_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('previous_position', sa.Integer(), nullable=True),
    sa.Column('position_change', sa.Integer(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tracking_id'], ['rank_trackings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_history_checked_at'), 'rank_history', ['checked_at'], unique=False)
    op.create_index(op.f('ix_rank_history_id'), 'rank_history', ['id'], unique=False)
    op.create_index(op.f('ix_rank_history_keyword'), 'rank_history', ['keyword'], unique=False)
    op.create_table('rank_tracking_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank_tracking_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('is_tracked', sa.Boolean(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rank_tracking_id'], ['rank_trackings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_tracking_keywords_id'), 'rank_tracking_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_rank_tracking_keywords_is_tracked'), 'rank_tracking_keywords', ['is_tracked'], unique=False)
    op.create_index(op.f('ix_rank_tracking_keywords_keyword'), 'rank_tracking_keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_rank_tracking_keywords_rank_tracking_id'), 'rank_tracking_keywords', ['rank_tracking_id'], unique=False)
    op.create_table('tracking_keywords',
    sa.Column('tracking_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['tracked_keywords.id'], ),
    sa.ForeignKeyConstraint(['tracking_id'], ['rank_trackings.id'], ),
    sa.PrimaryKeyConstraint('tracking_id', 'keyword_id')
    )
    op.create_table('rank_tracking_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank_tracking_keyword_id', sa.Integer(), nullable=False),
    sa.Column('search_engine', sa.String(length=50), nullable=False),
    sa.Column('current_rank', sa.Integer(), nullable=True),
    sa.Column('previous_rank', sa.Integer(), nullable=True),
    sa.Column('rank_change', sa.Integer(), nullable=True),
    sa.Column('found', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rank_tracking_keyword_id'], ['rank_tracking_keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_tracking_results_checked_at'), 'rank_tracking_results', ['checked_at'], unique=False)
    op.create_index(op.f('ix_rank_tracking_results_found'), 'rank_tracking_results', ['found'], unique=False)
    op.create_index(op.f('ix_rank_tracking_results_id'), 'rank_tracking_results', ['id'], unique=False)
    op.create_index(op.f('ix_rank_tracking_results_rank_tracking_keyword_id'), 'rank_tracking_results', ['rank_tracking_keyword_id'], unique=False)
    op.create_index(op.f('ix_rank_tracking_results_search_engine'), 'rank_tracking_results', ['search_engine'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rank_tracking_results_search_engine'), table_name='rank_tracking_results')
    op.drop_index(op.f('ix_rank_tracking_results_rank_tracking_keyword_id'), table_name='rank_tracking_results')
    op.drop_index(op.f('ix_rank_tracking_results_id'), table_name='rank_tracking_results')
    op.drop_index(op.f('ix_rank_tracking_results_found'), table_name='rank_tracking_results')
    op.drop_index(op.f('ix_rank_tracking_results_checked_at'), table_name='rank_tracking_results')
    op.drop_table('rank_tracking_results')
    op.drop_table('tracking_keywords')
    op.drop_index(op.f('ix_rank_tracking_keywords_rank_tracking_id'), table_name='rank_tracking_keywords')
    op.drop_index(op.f('ix_rank_tracking_keywords_keyword'), table_name='rank_tracking_keywords')
    op.drop_index(op.f('ix_rank_tracking_keywords_is_tracked'), table_name='rank_tracking_keywords')
    op.drop_index(op.f('ix_rank_tracking_keywords_id'), table_name='rank_tracking_keywords')
    op.drop_table('rank_tracking_keywords')
    op.drop_index(op.f('ix_rank_history_keyword'), table_name='rank_history')
    op.drop_index(op.f('ix_rank_history_id'), table_name='rank_history')
    op.drop_index(op.f('ix_rank_history_checked_at'), table_name='rank_history')
    op.drop_table('rank_history')
    op.drop_index(op.f('ix_keyword_history_id'), table_name='keyword_history')
    op.drop_index(op.f('ix_keyword_history_checked_at'), table_name='keyword_history')
    op.drop_table('keyword_history')
    op.drop_index(op.f('ix_embed_leads_id'), table_name='embed_leads')
    op.drop_index(op.f('ix_embed_leads_full_name'), table_name='embed_leads')
    op.drop_index(op.f('ix_embed_leads_email'), table_name='embed_leads')
    op.drop_index(op.f('ix_embed_leads_created_at'), table_name='embed_leads')
    op.drop_table('embed_leads')
    op.drop_index(op.f('ix_visitors_visited_at'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_ip_address'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_country_code'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_country'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_converted'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index(op.f('ix_tracked_keywords_keyword'), table_name='tracked_keywords')
    op.drop_index(op.f('ix_tracked_keywords_id'), table_name='tracked_keywords')
    op.drop_index(op.f('ix_tracked_keywords_domain'), table_name='tracked_keywords')
    op.drop_index(op.f('ix_tracked_keywords_created_at'), table_name='tracked_keywords')
    op.drop_table('tracked_keywords')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_rank_trackings_user_id'), table_name='rank_trackings')
    op.drop_index(op.f('ix_rank_trackings_status'), table_name='rank_trackings')
    op.drop_index(op.f('ix_rank_trackings_job_id'), table_name='rank_trackings')
    op.drop_index(op.f('ix_rank_trackings_id'), table_name='rank_trackings')
    op.drop_index(op.f('ix_rank_trackings_domain'), table_name='rank_trackings')
    op.drop_index(op.f('ix_rank_trackings_created_at'), table_name='rank_trackings')
    op.drop_table('rank_trackings')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_keyword_analyses_job_id'), table_name='keyword_analyses')
    op.drop_index(op.f('ix_keyword_analyses_id'), table_name='keyword_analyses')
    op.drop_index(op.f('ix_keyword_analyses_created_at'), table_name='keyword_analyses')
    op.drop_table('keyword_analyses')
    op.drop_index(op.f('ix_crawls_job_id'), table_name='crawls')
    op.drop_index(op.f('ix_crawls_id'), table_name='crawls')
    op.drop_index(op.f('ix_crawls_created_at'), table_name='crawls')
    op.drop_table('crawls')
    op.drop_index(op.f('ix_comparisons_job_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_created_at'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_backlink_analyses_job_id'), table_name='backlink_analyses')
    op.drop_index(op.f('ix_backlink_analyses_id'), table_name='backlink_analyses')
    op.drop_index(op.f('ix_backlink_analyses_created_at'), table_name='backlink_analyses')
    op.drop_table('backlink_analyses')
    op.drop_index(op.f('ix_audits_job_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_created_at'), table_name='audits')
    op.drop_table('audits')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_users_whop_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_embed_api_key'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
